
=================================== ERRORS ====================================
_________ ERROR collecting tests/test_extract_function_call_output.py _________
import file mismatch:
imported module 'test_extract_function_call_output' has this __file__ attribute:
  C:\DxO\DxO\tests\test_extract_function_call_output.py
which is not the same as the test file we want to collect:
  C:\DxO\tests\test_extract_function_call_output.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_________________ ERROR collecting tests/test_persistence.py __________________
import file mismatch:
imported module 'test_persistence' has this __file__ attribute:
  C:\DxO\DxO\tests\test_persistence.py
which is not the same as the test file we want to collect:
  C:\DxO\tests\test_persistence.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
=========================== short test summary info ===========================
ERROR tests/test_extract_function_call_output.py
ERROR tests/test_persistence.py
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!
2 errors in 0.28s
